# SUPER SUPER BINARY SEARCH DELUXE 2.5: THE LEGEND OF THE GOLDEN MAZASSUMNIDA,
# EPISODE 2: THE MAZWAETL UNIVERSE,
# PART 2: THE PARALLEL UNIVERSE AND THE LOST MAZASSUMNIDA: GAME OF THE YEAR EDITION
# 번외 문제(updown게임)

print(50)
