# 숫자의 개수
A = int(input())
B = int(input())
C = int(input())
Multiflication = str(A * B * C)
print(Multiflication.count("0"))
print(Multiflication.count("1"))
print(Multiflication.count("2"))
print(Multiflication.count("3"))
print(Multiflication.count("4"))
print(Multiflication.count("5"))
print(Multiflication.count("6"))
print(Multiflication.count("7"))
print(Multiflication.count("8"))
print(Multiflication.count("9"))
